import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import { Container } from "@components";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ProviderNextUI } from "@providers";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderNextUI>
          <Container>{children}</Container>
        </ProviderNextUI>
      </body>
    </html>
  );
}
